# What is a Feature

In [1]:
import pandas as pd

data = pd.DataFrame({
    "Age": [22, 35, 29, 41],
    "Income": [30000, 60000, 45000, 80000],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi"],
    "Has_Loan": [0, 1, 0, 1]
})

data

   Age  Income    City  Has_Loan
0   22   30000   Delhi         0
1   35   60000  Mumbai         1
2   29   45000    Pune         0
3   41   80000   Delhi         1

# Raw Data vs Processed Data

In [2]:
import pandas as pd

raw_data = pd.DataFrame({
    "Gender": ["male", "M", "Female", "FEMALE", "m"]
})

processed_data = raw_data.copy()
processed_data["Gender"] = (
    processed_data["Gender"]
    .str.lower()
    .replace({"m": "male", "female": "female"})
)

raw_data, processed_data

(   Gender
 0    male
 1       M
 2  Female
 3  FEMALE
 4       m,
    Gender
 0    male
 1    male
 2  female
 3  female
 4    male)

# Numerical Features

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Age": [25, 32, 40],
    "Salary": [40000, 55000, 70000]
})

df.dtypes

Age       int64
Salary    int64
dtype: object

# Categorical Features

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["HR", "Tech", "Finance", "Tech"]
})

df

  Department
0         HR
1       Tech
2    Finance
3       Tech

# Ordinal Features

In [5]:
import pandas as pd

df = pd.DataFrame({
    "Experience_Level": ["Junior", "Mid", "Senior", "Mid"]
})

mapping = {"Junior": 1, "Mid": 2, "Senior": 3}
df["Encoded_Level"] = df["Experience_Level"].map(mapping)

df

  Experience_Level  Encoded_Level
0           Junior              1
1              Mid              2
2           Senior              3
3              Mid              2

# Binary Features

In [6]:
import pandas as pd

df = pd.DataFrame({
    "Has_Credit_Card": [1, 0, 1, 1, 0]
})

df

   Has_Credit_Card
0                1
1                0
2                1
3                1
4                0

# Date and Time Features

In [7]:
import pandas as pd

df = pd.DataFrame({
    "Order_Date": pd.to_datetime([
        "2024-05-01",
        "2024-05-05",
        "2024-05-07"
    ])
})

df["Day"] = df["Order_Date"].dt.day
df["Weekday"] = df["Order_Date"].dt.day_name()

df

  Order_Date  Day    Weekday
0 2024-05-01    1  Wednesday
1 2024-05-05    5     Sunday
2 2024-05-07    7    Tuesday

# Text Features

In [8]:
import pandas as pd

df = pd.DataFrame({
    "Review": [
        "Amazing product and fast delivery",
        "Poor quality and bad packaging"
    ]
})

df["Word_Count"] = df["Review"].apply(lambda x: len(x.split()))
df["Char_Count"] = df["Review"].apply(len)

df

                              Review  Word_Count  Char_Count
0  Amazing product and fast delivery           5          33
1     Poor quality and bad packaging           5          30

# Image and Signal Features

In [9]:
from skimage import data
import numpy as np

image = data.astronaut()

mean_pixel = np.mean(image)
std_pixel = np.std(image)

mean_pixel, std_pixel

(114.59900410970052, 81.23036724707774)

# Feature Engineering vs Feature Selection vs Feature Extraction

In [10]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.feature_selection import SelectKBest, f_regression

df = pd.DataFrame({
    "x1": [1, 2, 3, 4],
    "x2": [2, 4, 6, 8],
    "y": [10, 20, 30, 40]
})

df["ratio"] = df["x2"] / df["x1"]

poly = PolynomialFeatures(degree=2)
poly_features = poly.fit_transform(df[["x1", "x2"]])

selector = SelectKBest(score_func=f_regression, k=1)
selected = selector.fit_transform(df[["x1", "x2"]], df["y"])

poly_features, selected

(array([[ 1.,  1.,  2.,  1.,  2.,  4.],
        [ 1.,  2.,  4.,  4.,  8., 16.],
        [ 1.,  3.,  6.,  9., 18., 36.],
        [ 1.,  4.,  8., 16., 32., 64.]]),
 array([[2],
        [4],
        [6],
        [8]]))

# Data Leakage

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "Age": [22, 30, 45, 50],
    "Income": [30000, 50000, 90000, 120000],
    "Approved": [0, 1, 1, 1]
})

X = df[["Age", "Income"]]
y = df["Approved"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

X_train.shape, X_test.shape

((3, 2), (1, 2))

# Understanding Missing Values

In [12]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [25, 30, np.nan, 45, 50],
    "Salary": [40000, np.nan, 60000, 80000, np.nan]
})

df

    Age   Salary
0  25.0  40000.0
1  30.0      NaN
2   NaN  60000.0
3  45.0  80000.0
4  50.0      NaN

# Dropping Missing Values

In [13]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [25, np.nan, 35, 40],
    "Salary": [50000, 60000, np.nan, 80000]
})

rows_dropped = df.dropna()
columns_dropped = df.dropna(axis=1)

rows_dropped, columns_dropped

(    Age   Salary
 0  25.0  50000.0
 3  40.0  80000.0,
 Empty DataFrame
 Columns: []
 Index: [0, 1, 2, 3])

# Mean and Median Imputation

In [14]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, 25, np.nan, 40, 45],
    "Salary": [30000, 45000, 50000, np.nan, 70000]
})

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df

    Age   Salary
0  20.0  30000.0
1  25.0  45000.0
2  32.5  50000.0
3  40.0  48750.0
4  45.0  70000.0

# Forward Fill and Backward Fill

In [15]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Temperature": [30, np.nan, np.nan, 35, 36]
})

forward_filled = df.fillna(method="ffill")
backward_filled = df.fillna(method="bfill")

forward_filled, backward_filled

(   Temperature
 0         30.0
 1         30.0
 2         30.0
 3         35.0
 4         36.0,
    Temperature
 0         30.0
 1         35.0
 2         35.0
 3         35.0
 4         36.0)

# KNN Imputation

In [16]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

df = pd.DataFrame({
    "Age": [25, 30, np.nan, 40],
    "Salary": [50000, 60000, 65000, np.nan]
})

imputer = KNNImputer(n_neighbors=2)
imputed_data = imputer.fit_transform(df)

pd.DataFrame(imputed_data, columns=df.columns)

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  27.5  65000.0
3  40.0  55000.0

# Regression-Based Imputation

In [17]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

df = pd.DataFrame({
    "Experience": [1, 2, 3, 4, 5],
    "Salary": [30000, 40000, np.nan, 60000, np.nan]
})

train = df.dropna()
test = df[df["Salary"].isna()]

model = LinearRegression()
model.fit(train[["Experience"]], train["Salary"])

df.loc[df["Salary"].isna(), "Salary"] = model.predict(test[["Experience"]])

df

   Experience   Salary
0           1  30000.0
1           2  40000.0
2           3  50000.0
3           4  60000.0
4           5  70000.0

# Missing Indicator Feature

In [18]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Income": [40000, np.nan, 60000, np.nan]
})

df["Income_Missing"] = df["Income"].isna().astype(int)

df

    Income  Income_Missing
0  40000.0               0
1      NaN               1
2  60000.0               0
3      NaN               1

# Understanding Categorical Data

In [19]:
import pandas as pd

df = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Pune", "Delhi"],
    "Category": ["A", "B", "A", "C"]
})

df

     City Category
0   Delhi        A
1  Mumbai        B
2    Pune        A
3   Delhi        C

# Label Encoding

In [20]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    "Department": ["HR", "Tech", "Finance", "Tech"]
})

encoder = LabelEncoder()
df["Department_Encoded"] = encoder.fit_transform(df["Department"])

df

  Department  Department_Encoded
0         HR                   1
1       Tech                   2
2    Finance                   0
3       Tech                   2

# One-Hot Encoding

In [21]:
import pandas as pd

df = pd.DataFrame({
    "Fuel_Type": ["Petrol", "Diesel", "EV", "Petrol"]
})

encoded = pd.get_dummies(df, columns=["Fuel_Type"])

encoded

   Fuel_Type_Diesel  Fuel_Type_EV  Fuel_Type_Petrol
0                 0             0                 1
1                 1             0                 0
2                 0             1                 0
3                 0             0                 1

# Ordinal Encoding

In [22]:
import pandas as pd

df = pd.DataFrame({
    "Education": ["School", "Graduate", "Postgraduate", "Graduate"]
})

order = {"School": 1, "Graduate": 2, "Postgraduate": 3}
df["Education_Encoded"] = df["Education"].map(order)

df

      Education  Education_Encoded
0        School                  1
1      Graduate                  2
2  Postgraduate                  3
3      Graduate                  2

# Frequency Encoding

In [23]:
import pandas as pd

df = pd.DataFrame({
    "Browser": ["Chrome", "Firefox", "Chrome", "Edge", "Chrome"]
})

freq = df["Browser"].value_counts(normalize=True)
df["Browser_Freq"] = df["Browser"].map(freq)

df

   Browser  Browser_Freq
0   Chrome           0.6
1  Firefox           0.2
2   Chrome           0.6
3     Edge           0.2
4   Chrome           0.6

# Target Encoding

In [24]:
import pandas as pd

df = pd.DataFrame({
    "Profession": ["Engineer", "Teacher", "Engineer", "Artist"],
    "Approved": [1, 0, 1, 0]
})

means = df.groupby("Profession")["Approved"].mean()
df["Profession_Target_Enc"] = df["Profession"].map(means)

df

  Profession  Approved  Profession_Target_Enc
0   Engineer         1                    1.0
1    Teacher         0                    0.0
2   Engineer         1                    1.0
3     Artist         0                    0.0

# Why Scaling is Needed

In [25]:
import pandas as pd

df = pd.DataFrame({
    "Age": [22, 35, 45, 60],
    "Salary": [30000, 55000, 90000, 120000]
})

df

   Age  Salary
0   22   30000
1   35   55000
2   45   90000
3   60  120000

# Standard Scaling

In [26]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.DataFrame({
    "Age": [22, 35, 45, 60],
    "Salary": [30000, 55000, 90000, 120000]
})

scaler = StandardScaler()
scaled = scaler.fit_transform(df)

pd.DataFrame(scaled, columns=df.columns)

        Age    Salary
0 -1.330798 -1.280583
1 -0.395643 -0.548821
2  0.323708  0.475645
3  1.402733  1.353759

# Min-Max Scaling

In [27]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.DataFrame({
    "Score": [45, 60, 75, 90]
})

scaler = MinMaxScaler()
scaled = scaler.fit_transform(df)

pd.DataFrame(scaled, columns=df.columns)

      Score
0  0.000000
1  0.333333
2  0.666667
3  1.000000

# Robust Scaling

In [28]:
import pandas as pd
from sklearn.preprocessing import RobustScaler

df = pd.DataFrame({
    "Income": [30000, 35000, 40000, 1500000]
})

scaler = RobustScaler()
scaled = scaler.fit_transform(df)

pd.DataFrame(scaled, columns=df.columns)

     Income
0 -0.020202
1 -0.006734
2  0.006734
3  3.939394

# MaxAbs Scaling

In [29]:
import pandas as pd
from sklearn.preprocessing import MaxAbsScaler

df = pd.DataFrame({
    "Balance": [-5000, -2000, 0, 3000, 8000]
})

scaler = MaxAbsScaler()
scaled = scaler.fit_transform(df)

pd.DataFrame(scaled, columns=df.columns)

   Balance
0   -0.625
1   -0.250
2    0.000
3    0.375
4    1.000

# Log Transformation

In [30]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Income": [20000, 30000, 50000, 1000000]
})

df["Log_Income"] = np.log1p(df["Income"])

df

    Income  Log_Income
0    20000    9.903538
1    30000   10.308986
2    50000   10.819798
3  1000000   13.815512

# Power Transformation (Yeo-Johnson)

In [31]:
import pandas as pd
from sklearn.preprocessing import PowerTransformer

df = pd.DataFrame({
    "Usage": [5, 7, 12, 30, 90]
})

transformer = PowerTransformer(method="yeo-johnson")
transformed = transformer.fit_transform(df)

pd.DataFrame(transformed, columns=df.columns)

      Usage
0 -1.267239
1 -0.805635
2 -0.144618
3  0.744394
4  1.473099

# Understanding Outliers

In [32]:
import pandas as pd

df = pd.DataFrame({
    "Transaction_Amount": [1200, 1500, 1800, 2000, 50000]
})

df

   Transaction_Amount
0                1200
1                1500
2                1800
3                2000
4               50000

# Z-Score Method

In [11]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Marks": [5, 6, 6, 6, 1999999999999998]
})

mean_value = df["Marks"].mean()
std_value = df["Marks"].std()

df["Z_Score"] = (df["Marks"] - mean_value) / std_value
print(df)
outliers = df[abs(df["Z_Score"]) > 1.5]

outliers

              Marks   Z_Score
0                 5 -0.447214
1                 6 -0.447214
2                 6 -0.447214
3                 6 -0.447214
4  1999999999999998  1.788854

              Marks   Z_Score
4  1999999999999998  1.788854

# IQR Method

In [12]:
import pandas as pd

df = pd.DataFrame({
    "Salary": [10, 30000, 32000, 35000, 37000, 150000]
})

Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)
IQR = Q3 - Q1

outliers = df[
    (df["Salary"] < Q1 - 1.5 * IQR) | (df["Salary"] > Q3 + 1.5 * IQR)]

outliers

   Salary
0      10
5  150000

# Winsorization (Capping)

In [35]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Income": [30000, 32000, 35000, 37000, 150000]
})

lower = df["Income"].quantile(0.05)
upper = df["Income"].quantile(0.95)

df["Income_Capped"] = np.clip(df["Income"], lower, upper)

df

   Income  Income_Capped
0   30000        30400.0
1   32000        32000.0
2   35000        35000.0
3   37000        37000.0
4  150000       127400.0

# Isolation Forest

In [36]:
import pandas as pd
from sklearn.ensemble import IsolationForest

df = pd.DataFrame({
    "Clicks": [10, 12, 11, 13, 120]
})

model = IsolationForest(contamination=0.2, random_state=42)
df["Outlier_Label"] = model.fit_predict(df[["Clicks"]])

df

/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

   Clicks  Outlier_Label
0      10              1
1      12              1
2      11              1
3      13              1
4     120             -1

# Local Outlier Factor

In [37]:
import pandas as pd
from sklearn.neighbors import LocalOutlierFactor

df = pd.DataFrame({
    "Distance": [100, 102, 98, 101, 250]
})

lof = LocalOutlierFactor(n_neighbors=2)
df["LOF_Label"] = lof.fit_predict(df[["Distance"]])

df

   Distance  LOF_Label
0       100          1
1       102          1
2        98          1
3       101          1
4       250         -1

# Remove vs Keep vs Cap Decision

In [13]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Purchase_Amount": [500, 700, 800, 1200, 50000]
})

threshold = df["Purchase_Amount"].quantile(0.99)
print(threshold)

filtered = df[df["Purchase_Amount"] <= threshold]
capped = df.copy()
capped["Purchase_Amount"] = np.minimum(capped["Purchase_Amount"], threshold)

filtered, capped

48048.0

(   Purchase_Amount
 0              500
 1              700
 2              800
 3             1200,
    Purchase_Amount
 0            500.0
 1            700.0
 2            800.0
 3           1200.0
 4          48048.0)

# Creating Ratio Features

In [39]:
import pandas as pd

df = pd.DataFrame({
    "Total_Sales": [20000, 50000, 80000],
    "Total_Customers": [100, 250, 400]
})

df["Sales_per_Customer"] = df["Total_Sales"] / df["Total_Customers"]

df

   Total_Sales  Total_Customers  Sales_per_Customer
0        20000              100               200.0
1        50000              250               200.0
2        80000              400               200.0

# Aggregation-Based Features

In [40]:
import pandas as pd

df = pd.DataFrame({
    "City": ["Delhi", "Delhi", "Mumbai", "Mumbai"],
    "Order_Value": [500, 700, 400, 900]
})

city_avg = df.groupby("City")["Order_Value"].mean()
df["City_Avg_Order"] = df["City"].map(city_avg)

df

     City  Order_Value  City_Avg_Order
0   Delhi          500           600.0
1   Delhi          700           600.0
2  Mumbai          400           650.0
3  Mumbai          900           650.0

# Difference from Group Mean

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["HR", "HR", "Tech", "Tech"],
    "Salary": [40000, 45000, 70000, 75000]
})

dept_mean = df.groupby("Department")["Salary"].mean()
print(dept_mean)
df["Salary_Deviation"] = df["Salary"] - df["Department"].map(dept_mean)

df

Department
HR      42500.0
Tech    72500.0
Name: Salary, dtype: float64

  Department  Salary  Salary_Deviation
0         HR   40000           -2500.0
1         HR   45000            2500.0
2       Tech   70000           -2500.0
3       Tech   75000            2500.0

# Polynomial Interaction Features

In [42]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures

df = pd.DataFrame({
    "x1": [1, 2, 3],
    "x2": [2, 4, 6]
})

poly = PolynomialFeatures(degree=2, include_bias=False)
poly_features = poly.fit_transform(df)

pd.DataFrame(poly_features, columns=poly.get_feature_names_out())

    x1   x2  x1^2  x1 x2  x2^2
0  1.0  2.0   1.0    2.0   4.0
1  2.0  4.0   4.0    8.0  16.0
2  3.0  6.0   9.0   18.0  36.0

# Boolean Rule-Based Features

In [15]:
import pandas as pd

df = pd.DataFrame({
    "Age": [22, 35, 60],
    "Income": [30000, 60000, 40000]
})

df["High_Risk"] = ((df["Age"] > 50) & (df["Income"] < 50000)).astype(int)

df

   Age  Income  High_Risk
0   22   30000          0
1   35   60000          0
2   60   40000          1

# Cumulative Features

In [44]:
import pandas as pd

df = pd.DataFrame({
    "Daily_Sales": [100, 150, 200, 250]
})

df["Cumulative_Sales"] = df["Daily_Sales"].cumsum()

df

   Daily_Sales  Cumulative_Sales
0          100               100
1          150               250
2          200               450
3          250               700

# Rank-Based Features

In [16]:
import pandas as pd

df = pd.DataFrame({
    "Score": [88, 92, 75, 90]
})

df["Rank"] = df["Score"].rank()

df

   Score  Rank
0     88   2.0
1     92   4.0
2     75   1.0
3     90   3.0

# Understanding Feature Transformation

In [46]:
import pandas as pd

df = pd.DataFrame({
    "Income": [25000, 40000, 60000, 120000]
})

df

   Income
0   25000
1   40000
2   60000
3  120000

# Log Transformation

In [47]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Income": [25000, 40000, 60000, 120000]
})

df["Log_Income"] = np.log(df["Income"])

df

   Income  Log_Income
0   25000   10.126631
1   40000   10.596635
2   60000   11.002100
3  120000   11.695247

# Square Root Transformation

In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Sales": [25000, 40000, 60000, 120000]
})

df["Sqrt_Sales"] = np.sqrt(df["Sales"])

df

    Sales  Sqrt_Sales
0   25000  158.113883
1   40000  200.000000
2   60000  244.948974
3  120000  346.410162

# Binning using Equal Width

In [49]:
import pandas as pd

df = pd.DataFrame({
    "Age": [18, 25, 33, 47, 60]
})

df["Age_Bin"] = pd.cut(df["Age"], bins=3)

df

   Age         Age_Bin
0   18  (17.958, 32.0]
1   25  (17.958, 32.0]
2   33    (32.0, 46.0]
3   47    (46.0, 60.0]
4   60    (46.0, 60.0]

# Binning using Equal Frequency

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Score": [45, 50, 60, 61, 70, 85]
})

df["Score_Bin"] = pd.qcut(df["Score"], q=3)

df

   Score         Score_Bin
0     45  (44.999, 56.667]
1     50  (44.999, 56.667]
2     60    (56.667, 64.0]
3     61    (56.667, 64.0]
4     70      (64.0, 85.0]
5     85      (64.0, 85.0]

# Principal Component Analysis (PCA)

In [54]:
import pandas as pd
from sklearn.decomposition import PCA

df = pd.DataFrame({
    "F1": [1, 2, 3, 4],
    "F2": [2, 4, 6, 8],
    "F3": [5, 6, 7, 8]
})

pca = PCA(n_components=2)
components = pca.fit_transform(df)

pd.DataFrame(components, columns=["PC1", "PC2"])

        PC1  PC2
0  3.674235  0.0
1  1.224745  0.0
2 -1.224745  0.0
3 -3.674235 -0.0

# Explained Variance Analysis

In [55]:
import pandas as pd
from sklearn.decomposition import PCA

df = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": [2, 4, 6, 8],
    "C": [1, 3, 5, 7]
})

pca = PCA()
pca.fit(df)

pca.explained_variance_ratio_

array([1., 0., 0.])

# Linear Discriminant Analysis (LDA)

In [57]:
import pandas as pd
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X = pd.DataFrame({
    "F1": [1, 2, 3, 4, 5],
    "F2": [2, 4, 6, 8, 10]
})

y = [0, 0, 1, 1, 1]

lda = LinearDiscriminantAnalysis(n_components=1)
reduced = lda.fit_transform(X, y)

reduced

array([[-2.19089023],
       [-1.09544512],
       [ 0.        ],
       [ 1.09544512],
       [ 2.19089023]])

# Feature Agglomeration

In [13]:
import pandas as pd
from sklearn.cluster import FeatureAgglomeration

df = pd.DataFrame({
    "F1": [1, 2, 3],
    "F2": [2, 4, 6],
    "F3": [10, 20, 30],
    "F4": [11, 21, 31]
    
})

agglo = FeatureAgglomeration(n_clusters=2)
reduced = agglo.fit_transform(df)

pd.DataFrame(reduced)

     0     1
0  1.5  10.5
1  3.0  20.5
2  4.5  30.5

# Understanding Feature Selection

In [59]:
import pandas as pd

df = pd.DataFrame({
    "Age": [22, 30, 45, 50],
    "Income": [30000, 50000, 90000, 120000],
    "Score": [650, 700, 720, 680],
    "Approved": [0, 1, 1, 1]
})

df

   Age  Income  Score  Approved
0   22   30000    650         0
1   30   50000    700         1
2   45   90000    720         1
3   50  120000    680         1

# Variance Threshold

In [60]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

df = pd.DataFrame({
    "A": [1, 1, 1, 1],
    "B": [10, 12, 11, 13],
    "C": [5, 6, 7, 8]
})

selector = VarianceThreshold(threshold=0.0)
selected = selector.fit_transform(df)

selected

array([[10,  5],
       [12,  6],
       [11,  7],
       [13,  8]])

# Correlation-Based Feature Selection

In [3]:
import pandas as pd

df = pd.DataFrame({
    "X1": [1, 2, 3, 4],
    "X2": [2, 4, 6, 8],
    "X3": [21, 69, 77, 51],
    "y": [10, 20, 30, 40]
})

correlation = df.corr()
correlation

         X1       X2       X3        y
X1  1.00000  1.00000  0.50934  1.00000
X2  1.00000  1.00000  0.50934  1.00000
X3  0.50934  0.50934  1.00000  0.50934
y   1.00000  1.00000  0.50934  1.00000

# SelectKBest

In [62]:
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_regression

df = pd.DataFrame({
    "X1": [1, 2, 3, 4],
    "X2": [2, 1, 2, 1],
    "X3": [5, 6, 7, 8],
    "y": [10, 20, 30, 40]
})

X = df.drop("y", axis=1)
y = df["y"]

selector = SelectKBest(score_func=f_regression, k=2)
selected = selector.fit_transform(X, y)

selected

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Recursive Feature Elimination

In [63]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

df = pd.DataFrame({
    "A": [1, 2, 3, 4],
    "B": [2, 3, 4, 5],
    "C": [5, 6, 7, 8],
    "y": [10, 20, 30, 40]
})

X = df.drop("y", axis=1)
y = df["y"]

model = LinearRegression()
rfe = RFE(model, n_features_to_select=2)
selected = rfe.fit_transform(X, y)

selected

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

# L1 Regularization (Lasso)

In [64]:
import pandas as pd
from sklearn.linear_model import Lasso

df = pd.DataFrame({
    "X1": [1, 2, 3, 4],
    "X2": [2, 4, 6, 8],
    "X3": [1, 0, 1, 0],
    "y": [10, 20, 30, 40]
})

X = df.drop("y", axis=1)
y = df["y"]

model = Lasso(alpha=0.1)
model.fit(X, y)

model.coef_

array([ 0.  ,  4.98, -0.  ])

# Tree-Based Feature Importance

In [65]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

X = pd.DataFrame({
    "Age": [22, 30, 45, 50],
    "Income": [30000, 50000, 90000, 120000],
    "Score": [650, 700, 720, 680]
})

y = [0, 1, 1, 1]

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

model.feature_importances_

array([0.28985507, 0.42028986, 0.28985507])